name: Release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    strategy:
      matrix:
        os:
          - name: linux
            runner: ubuntu-latest
          - name: macos
            runner: macos-latest
          - name: windows
            runner: windows-latest
    runs-on: ${{ matrix.os.runner }}

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile

      - name: Typecheck
        run: bun run typecheck

      - name: Run tests
        run: bun run test

      - name: Build binary
        run: bun run build

      - uses: actions/upload-artifact@v4
        with:
          name: zex-${{ matrix.os.name }}
          path: dist/zex*

  publish:
    runs-on: ubuntu-latest
    needs: [release]
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: zex-*
          merge-multiple: true

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: zex-*
          generate_release_notes: true
